// lib/data.ts
import { Agent, Task, Activity, Column } from '@/types';

export const columns: Column[] = [
  { id: 'inbox', title: 'Inbox', color: '#64748b' },
  { id: 'assigned', title: 'Assigned', color: '#3b82f6' },
  { id: 'in_progress', title: 'In Progress', color: '#eab308' },
  { id: 'review', title: 'Review', color: '#a855f7' },
  { id: 'done', title: 'Done', color: '#22c55e' },
];

export const initialAgents: Agent[] = [
  {
    id: 'jarvis',
    name: 'Jarvis',
    role: 'Squad Lead',
    emoji: '🎯',
    status: 'active',
    statusText: 'Coordinating',
    color: '#6366f1',
  },
  {
    id: 'shuri',
    name: 'Shuri',
    role: 'Product Analyst',
    emoji: '🔍',
    status: 'active',
    statusText: 'QA Complete',
    color: '#ec4899',
  },
  {
    id: 'fury',
    name: 'Fury',
    role: 'Researcher',
    emoji: '📚',
    status: 'active',
    statusText: 'Research Done',
    color: '#f97316',
  },
  {
    id: 'loki',
    name: 'Loki',
    role: 'Content Writer',
    emoji: '✍️',
    status: 'active',
    statusText: 'Content Ready',
    color: '#10b981',
  },
  {
    id: 'vision',
    name: 'Vision',
    role: 'SEO/Marketing',
    emoji: '📈',
    status: 'active',
    statusText: 'SEO Complete',
    color: '#8b5cf6',
  },
  {
    id: 'marty',
    name: 'Marty',
    role: 'Coding Best Practices',
    emoji: '🛡️',
    status: 'active',
    statusText: 'Ready for Tasks',
    color: '#06b6d4',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Setup Multi-Agent System',
    description: 'Implement the multi-agent structure with 6 agents',
    status: 'done',
    priority: 'high',
    assignee: 'jarvis',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'task-2',
    title: 'Create Content Tools',
    description: 'Develop tools and templates for Loki',
    status: 'done',
    priority: 'high',
    assignee: 'loki',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'task-3',
    title: 'Research Robotics Market',
    description: 'Deep research on robotics market trends',
    status: 'done',
    priority: 'high',
    assignee: 'fury',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'task-4',
    title: 'Deploy Newsletter Website',
    description: 'Deploy landing page to Vercel',
    status: 'done',
    priority: 'high',
    assignee: 'jarvis',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'task-5',
    title: 'Write First Premium Newsletter',
    description: 'Create first premium newsletter edition',
    status: 'done',
    priority: 'high',
    assignee: 'loki',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'task-6',
    title: 'QA Review Newsletter',
    description: 'Quality assurance review of newsletter',
    status: 'done',
    priority: 'medium',
    assignee: 'shuri',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 21600000).toISOString(),
  },
  {
    id: 'task-7',
    title: 'SEO Optimization',
    description: 'Audit and optimize website for search engines',
    status: 'done',
    priority: 'high',
    assignee: 'vision',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: 'task-10',
    title: 'Interactive Admin Dashboard',
    description: 'Build interactive Next.js dashboard with drag-and-drop',
    status: 'done',
    priority: 'high',
    assignee: 'marty',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString(),
  },
];

export const initialActivities: Activity[] = [
  {
    id: 'act-1',
    agentId: 'marty',
    agentName: 'Marty',
    agentEmoji: '🛡️',
    action: 'completed',
    target: 'Interactive Admin Dashboard',
    timestamp: new Date().toISOString(),
  },
  {
    id: 'act-2',
    agentId: 'vision',
    agentName: 'Vision',
    agentEmoji: '📈',
    action: 'completed',
    target: 'SEO Optimization',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: 'act-3',
    agentId: 'shuri',
    agentName: 'Shuri',
    agentEmoji: '🔍',
    action: 'approved newsletter with score',
    target: '9/10',
    timestamp: new Date(Date.now() - 21600000).toISOString(),
  },
  {
    id: 'act-4',
    agentId: 'loki',
    agentName: 'Loki',
    agentEmoji: '✍️',
    action: 'completed',
    target: 'Premium Newsletter',
    timestamp: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'act-5',
    agentId: 'fury',
    agentName: 'Fury',
    agentEmoji: '📚',
    action: 'delivered',
    target: 'Robotics Market Research',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
  },
];
